### PR TITLE
Deleting unused images + Footer Update

### PR DESCRIPTION
**Pull request by strubium**

### CODE REVIEW

**Comment by strubium** [comment]
pain

**Comment by markgyoni** [comment]
> pain

same

**Comment by strubium** [comment]
MERGE ME



AAAAAAAAAAA

**Comment by markgyoni** [comment]
> MERGE ME
> 
> 
> 
> AAAAAAAAAAA

I will if I caaaaaaaan. I need something better than a phone lol.

**Comment by strubium** [comment]
> > MERGE ME
> > AAAAAAAAAAA
> 
> I will if I caaaaaaaan. I need something better than a phone lol.

Thankkkk yoooooouuuuu

**Review by markgyoni — APPROVED** [review]
Alright, thanks for the PR!

**Pull request merged**
