### PR TITLE
I have no life at this point

### PR DESCRIPTION
**Pull request by strubium**
Many small changes to mods + Info on war

### CODE REVIEW

**Comment by strubium** [comment]
The discord users online thing may not display correctly, I have no way of testing it

**Comment by markgyoni** [comment]
> The discord users online thing may not display correctly, I have no way of testing it 

I think you can still do npm i and npm start to start a dev server locally.

**Comment by strubium** [comment]
> > The discord users online thing may not display correctly, I have no way of testing it
> 
> I think you can still do npm i and npm start to start a dev server locally.

Tested it, it looks weird so I removed it, 100% ready from merge.

**Comment by markgyoni** [comment]
> > > The discord users online thing may not display correctly, I have no way of testing it
> > 
> > 
> > I think you can still do npm i and npm start to start a dev server locally.
> 
> Tested it, it looks weird so I removed it, 100% ready from merge.

Alright, thank you so much. May I ask your name on the Discord server? You'll definately get something for these, I just have to figure out what.

**Review by markgyoni — APPROVED** [review]

**Comment by strubium** [comment]
> 

Stevemcgeve/Smeagle

**Comment by markgyoni** [comment]
> > 
> 
> Stevemcgeve/Smeagle

Cool, thanks.

**Comment by strubium** [comment]
> > > 
> > 
> > 
> > Stevemcgeve/Smeagle
> 
> Cool, thanks.

You're welcome!

**Pull request merged**
